FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

RUN mkdir /var/www/laravel/public -p && touch /var/www/laravel/public/index.php

# ENTRYPOINT ["/docker-entrypoint.sh"] ## Not required
# CMD ["nginx", "-g", "daemon off;"] ## Not required#docker build -t walopes/nginx:prod . -f Dockerfile.prod
#docker network create laranet
#docker run -d --network laranet --name laravel walopes/laravel:prod
