FROM php:7.4-cli

WORKDIR /var/www
RUN apt-get update && \
	apt-get install git libzip-dev -y && \
	docker-php-ext-install zip

# Installing Compose
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
	php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
	php composer-setup.php && \
	php -r "unlink('composer-setup.php');"

RUN php composer.phar create-project --prefer-dist laravel/laravel laravel

ENTRYPOINT [ "php", "laravel/artisan", "serve" ]
CMD [ "--host=0.0.0.0" ]

#docker run -it  --name php php:7.4-cli bash
#docker build -t walopes/laravel:latest .
#docker run --rm --name laravel -p 8000:8000 walopes/laravel
#docker run --rm -d --name laravel -p 8000:8000 walopes/laravel
